cygwin kludge, bc I installed python thru windows

diff --git a/sspa b/sspa
--- a/sspa
+++ b/sspa
@@ -14,12 +14,12 @@ function check_python() {
 }
 
 function check_aws() {
-  if ! which aws > /dev/null; then
-    echo "Can't find AWS CLI. Install 'awscli' using pip."
+  if ! which aws.cmd > /dev/null; then
+    echo "Can't find aws.cmd CLI. Install 'awscli' using pip."
     exit 1
   fi
-  if ! aws configure list --profile $profile > /dev/null; then
-    echo "Run \`aws configure --profile $profile\` to create it"
+  if ! aws.cmd configure list --profile $profile > /dev/null; then
+    echo "Run \`aws.cmd configure --profile $profile\` to create it"
     exit 1
   fi
 }
@@ -54,8 +54,8 @@ function create_s3_bucket() {
   local bucket_path=conf/s3/${bucket_name}
   # The s3 command doesn't output JSON :-/
   if [[ ! -e ${bucket_path}/endpoint.txt ]]; then
-    aws --profile $profile s3 mb $bucket_uri && mkdir -p ${bucket_path}
-    local region=$(aws --profile $profile configure get region)
+    aws.cmd --profile $profile s3 mb $bucket_uri && mkdir -p ${bucket_path}
+    local region=$(aws.cmd --profile $profile configure get region)
     local endpoint="http://${1}.s3-website-${region}.amazonaws.com"
     echo "$endpoint" > ${bucket_path}/endpoint.txt
     echo "Website endpoint is: $endpoint"
@@ -65,7 +65,7 @@ function create_s3_bucket() {
 function webify_bucket() {
   local bucket_name=$1
   local bucket_uri="s3://${bucket_name}"
-  aws --profile $profile s3 website \
+  aws.cmd --profile $profile s3 website \
     --index-document index.html \
     --error-document error.html \
     $bucket_uri
@@ -77,7 +77,7 @@ function deploy_s3_bucket() {
     bucket_name=$(basename $bucket_name)
   fi
   local bucket_uri="s3://${1}"
-  aws --profile $profile s3 sync public/ $bucket_uri --acl public-read
+  aws.cmd --profile $profile s3 sync public/ $bucket_uri --acl public-read
 }
 
 function generate_assume_role_policy() {
@@ -142,7 +142,7 @@ function create_cognito_auth_role() {
     local role_name="${pool_name}_cognito_authenticated"
     echo "Creaing role: $role_name"
     # Might be able to use the create_iam_role function for this
-    aws --profile $profile iam create-role \
+    aws.cmd --profile $profile iam create-role \
       --role-name "$role_name" \
       --assume-role-policy-document "file://${identity_pool_dir}/assume_role_policy.json" \
       > ${identity_pool_dir}/role_info.json
@@ -160,7 +160,7 @@ function create_identity_pool() {
   local identity_pool_name=$(basename $identity_pool_dir)
   if [[ ! -s ${identity_pool_dir}/pool_info.json ]]; then
     echo "Creating identity pool: $identity_pool_name"
-    aws --profile $profile cognito-identity create-identity-pool \
+    aws.cmd --profile $profile cognito-identity create-identity-pool \
       --identity-pool-name $identity_pool_name \
       --cli-input-json "file://${identity_pool_dir}/config.json" \
       > ${identity_pool_dir}/pool_info.json
@@ -170,7 +170,7 @@ function create_identity_pool() {
   local pool_id=$(support/jsed.py ${identity_pool_dir}/pool_info.json 'IdentityPoolId')
   local role_arn=$(support/jsed.py ${identity_pool_dir}/role_info.json 'Role.Arn')
   echo "Updating identity pool roles"
-  aws --profile $profile cognito-identity set-identity-pool-roles \
+  aws.cmd --profile $profile cognito-identity set-identity-pool-roles \
     --identity-pool-id ${pool_id} \
     --roles authenticated=${role_arn}
 }
@@ -180,15 +180,15 @@ function create_table() {
   local table_name=$(basename $table_dir)
   local role_name="${2}_cognito_authenticated"
   if [[ ! -s ${table_dir}/table_info.json ]]; then
-    aws --profile $profile dynamodb create-table \
+    aws.cmd --profile $profile dynamodb create-table \
       --table-name $table_name \
       --cli-input-json "file://${table_dir}/config.json" \
       > ${table_dir}/table_info.json
 
     echo -n "Waiting for table creation..."
-    aws --profile $profile dynamodb describe-table --table-name "$table_name" > ${table_dir}/table_info.json
+    aws.cmd --profile $profile dynamodb describe-table --table-name "$table_name" > ${table_dir}/table_info.json
     while [[ "$(support/jsed.py ${table_dir}/table_info.json 'Table.TableStatus')" != "ACTIVE" ]]; do
-      aws --profile $profile dynamodb describe-table --table-name "$table_name" > ${table_dir}/table_info.json
+      aws.cmd --profile $profile dynamodb describe-table --table-name "$table_name" > ${table_dir}/table_info.json
       echo -n .
     done
     echo "...done!"
@@ -196,7 +196,7 @@ function create_table() {
 
   local table_arn=$(support/jsed.py ${table_dir}/table_info.json 'Table.TableArn')
   generate_table_policy ${table_arn} > ${table_dir}/role_policy.json
-  aws --profile $profile iam put-role-policy \
+  aws.cmd --profile $profile iam put-role-policy \
     --policy-document file://${table_dir}/role_policy.json \
     --role-name ${role_name} \
     --policy-name ${table_name}_table_access
@@ -221,7 +221,7 @@ function build_bundle() {
 
 function deploy_bundle {
   for fn in `ls conf/lambda/functions`; do
-    aws --profile $profile lambda update-function-code \
+    aws.cmd --profile $profile lambda update-function-code \
       --function-name $fn \
       --zip-file "fileb://services/archive.zip" > conf/lambda/functions/$fn/info.json
   done
@@ -244,7 +244,7 @@ function create_iam_role() {
   local policy_document=$2
   mkdir -p $role_dir
   if [[ ! -e ${role_dir}/info.json ]]; then
-    aws --profile $profile iam create-role \
+    aws.cmd --profile $profile iam create-role \
       --role-name "$role_name" \
       --assume-role-policy-document "${policy_document}" \
       > ${role_dir}/info.json
@@ -257,13 +257,13 @@ function create_lambda_service() {
   create_iam_role lambda_exec "file://conf/iam/policies/lambda_trust.json"
   echo -n "Waiting for IAM Role to become available..."
   local role_arn=$(support/jsed.py conf/iam/roles/${app_name}_lambda_exec/info.json 'Role.Arn')
-  while ! aws --profile $profile iam get-role --role-name ${app_name}_lambda_exec &> /dev/null; do
+  while ! aws.cmd --profile $profile iam get-role --role-name ${app_name}_lambda_exec &> /dev/null; do
     echo -n .
   done
   sleep 5 # See issue #17
   echo "...done!"
   if [[ ! -e ${service_dir}/info.json ]]; then
-    aws --profile $profile lambda create-function \
+    aws.cmd --profile $profile lambda create-function \
       --function-name ${function_name} \
       --role ${role_arn} \
       --runtime nodejs4.3 \
